"""Auto migration

Revision ID: 8006d73c4f57
Revises: deb322ae6473
Create Date: 2024-11-09 17:15:02.271834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8006d73c4f57'
down_revision: Union[str, None] = 'deb322ae6473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    # ### end Alembic commands ###
