"""Auto migration

Revision ID: fbfa415d9abf
Revises: 5fbc0d4fd99d
Create Date: 2024-10-23 16:30:29.427596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfa415d9abf'
down_revision: Union[str, None] = '5fbc0d4fd99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_tasks_discription', table_name='tasks')
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.drop_column('tasks', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.create_index('ix_tasks_discription', 'tasks', ['discription'], unique=False)
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
